services:
  - type: web
    name: bot-trends-brasil
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot_com_alertas.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
