services:
  - type: web
    name: bot-trends-brasil
    env: python
    region: oregon
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot_com_alertas.py
